CashRegisterAPI/Models/ErrorViewModel.cs
namespace CashRegisterAPI.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

CashRegisterAPI/Models/ItemType.cs
namespace CashRegisterAPI.Models;

public class ItemType {
        public int Id { get; set; }
        public string Description { get; set; }
}

CashRegisterAPI/Models/Search.cs
using System.ComponentModel.DataAnnotations;

namespace CashRegisterAPI.Models
{
    public class Search
    {
        public string Name { get; set; }
    }
}

CashRegisterAPI/Models/ShoppingListItem.cs
namespace CashRegisterAPI.Models
{
    public class ShoppingListItem
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int Quantity { get; set; }
    }
}

CashRegisterAPI/Models/StoreItem.cs
namespace CashRegisterAPI.Models
{
    public class StoreItem
    {
        public StoreItem (int Id, string Description, int UOM, int TypeId, decimal Price) {
            this.Id = Id;
            this.Description = Description;
            this.UOM = UOM;
            // this.Type = Type;
            this.TypeId = TypeId;
            this.Price = Price;
        }
        
        public int Id { get; set; }

        public string Description { get; set; }

        public int UOM { get; set; }

        // public ItemType Type { get; set; }
        public int TypeId { get; set; }

        public decimal Price { get; set; }
    }
}

CashRegisterAPI/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CashRegisterAPI.Models;

namespace CashRegisterAPI.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

CashRegisterAPI/Controllers/SearchController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CashRegisterAPI.Models;

namespace CashRegisterAPI.Controllers;

public class SearchController : Controller
{
    private readonly CashRegisterAPIContext _context;

    public SearchController(CashRegisterAPIContext context)
        {
            _context = context;
        }

    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    public async Task<IActionResult> Search(string Name)
        {
            return NotFound();   
        }
}

CashRegisterAPI/Controllers/ShoppingListController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CashRegisterAPI.Models;

namespace CashRegisterAPI.Controllers
{
    public class ShoppingListController : Controller
    {
        private readonly CashRegisterAPIContext _context;

        public ShoppingListController(CashRegisterAPIContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.ShoppingListItem.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.ShoppingListItem
                .FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Quantity")] ShoppingListItem item)
        {
            if (ModelState.IsValid)
            {
                _context.Add(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.ShoppingListItem.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Quantity")] ShoppingListItem item)
        {
            if (id != item.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.ShoppingListItem
                .FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var item = await _context.ShoppingListItem.FindAsync(id);
            _context.ShoppingListItem.Remove(item);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(int id)
        {
            return _context.ShoppingListItem.Any(e => e.Id == id);
        }
    }
}

CashRegisterAPI/Controllers/StoreController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CashRegisterAPI.Models;
using Microsoft.EntityFrameworkCore;

namespace CashRegisterAPI.Controllers;

public class StoreController : Controller
{
    private readonly CashRegisterAPIContext _context;

    public StoreController(CashRegisterAPIContext context)
        {
            _context = context;
        }

    public async Task<IActionResult> IndexAsync()
    {
        ViewData["StoreItems"] = await  _context.StoreItem.ToListAsync();

        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

CashRegisterAPI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome in the supermarket</h1>
    <p>On the top of this page, you can navigate within the tabs.</p>
</div>

CashRegisterAPI/Views/Search/Index.cshtml
@model CashRegisterAPI.Models.Search

@{
    ViewData["Title"] = "Search";
}

<div class="text-center">
    <h1 class="display-4">Search the supermarket</h1>
    <p>What are you looking for?</p>
    
    <form asp-action="Search">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" style="margin-left:auto;margin-right:auto;width:25%" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Search" class="btn btn-primary" />
        </div>
    </form>
</div>

CashRegisterAPI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CashRegisterAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CashRegisterAPI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CashRegisterAPI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">Store</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="Index">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingList" asp-action="Index">Shopping list</a>
                        </li>
                     
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            2022 - Jelle de Beer
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CashRegisterAPI/Views/ShoppingList/Create.cshtml
@model CashRegisterAPI.Models.ShoppingListItem

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CashRegisterAPI/Views/ShoppingList/Delete.cshtml
@model CashRegisterAPI.Models.ShoppingListItem

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CashRegisterAPI/Views/ShoppingList/Details.cshtml
@model CashRegisterAPI.Models.ShoppingListItem

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CashRegisterAPI/Views/ShoppingList/Edit.cshtml
@model CashRegisterAPI.Models.ShoppingListItem

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CashRegisterAPI/Views/ShoppingList/Get.cshtml
@{
    ViewData["Title"] = "Pricing documentation";
}

<h2>Pricing API</h2><br>

<p>You asked product @ViewData["productName"]</p> 

<p>@ViewData["quantity"] times</p>

CashRegisterAPI/Views/ShoppingList/Index.cshtml
@model IEnumerable<CashRegisterAPI.Models.ShoppingListItem>

@{
    ViewData["Title"] = "ShoppingList";
}

<h1>Fill in your shopping list here.</h1>

<p>
    <a asp-action="Create">Add a product to  list</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model is not null) { 
            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

CashRegisterAPI/Views/Store/Index.cshtml
@model CashRegisterAPI.Models.StoreItem

@{
    ViewData["Title"] = "Store";
}

<div class="text-center">
    <h1 class="display-4">Products of the supermarket</h1>
    <div class="row">
    @if (ViewData["StoreItems"] is not null) {
        @foreach (StoreItem storeItem in (List<StoreItem>)ViewData["StoreItems"])
        {
           
           <div class="card" style="width: 18rem; margin: 5px;">
               <div class="card-body"> 
                   <b class="card-title">@storeItem.Description</b>
                   <p class="card-text">Content: @storeItem.UOM </p>
                   <p class="card-text">&euro; @storeItem.Price </p>
               </div>

           </div>
        }  
    }
    </div>
</div>
  
  
  